package api

import (
	"errors"
	"fmt"
	"log/slog"
	"net/http"

	"github.com/jackc/pgx/v5"

	"github.com/jsmith212/bakery/internal/auth"
	"github.com/jsmith212/bakery/internal/db/repository"
)

// ---------------------------------------------------------------------------
// The SITE role: hybrid, like org membership, and for the same reason -- a
// deployment must be able to appoint a platform admin without an LDAP round trip.
//
// It is also the most dangerous role in the installation, so the trade is made
// SAFE by being made VISIBLE. Three facts hold it up, and none of them is a
// convention:
//
//  1. A LOCAL grant and a CLAIM are separate columns, and the effective role is
//     greatest(oidc, local), generated by the database. The reconciler names only
//     the oidc_* half; these handlers name only the local half. Neither can clobber
//     the other, because neither statement names the other's columns.
//
//  2. The LISTING reports the source of every admin. The one real risk in a hybrid
//     site role is a local grant that outlives the LDAP revocation meant to remove
//     it -- and that state is inherent, not preventable, so it is surfaced instead.
//     `ldap: platform-admins` beside `local: granted by jsmith on 2026-07-12`.
//
//  3. AN API KEY CAN NEVER GRANT A SITE ROLE. These routes are AccessSiteAdmin, and
//     the guard admits a key to AccessAuthenticated and nowhere else -- and an
//     API-key principal's IsSiteAdmin() is false even when the owning human is a
//     site admin. Two independent refusals, because a delegation that could mint a
//     site admin would not be a delegation, it would be a master key with a
//     succession plan.
//
// What is NOT here: any way to grant the FIRST site admin. That endpoint cannot
// exist -- it would have to be reachable without already being a site admin, which
// is an unauthenticated privilege escalation however it is dressed. The bootstrap
// path is `bakery user site-admin <email>`, which needs DB_URL and no session at
// all. See config.UserCmd.
// ---------------------------------------------------------------------------

// handleListSiteAdmins lists every site admin, WITH THE SOURCE OF EACH. Site admin.
//
// This is the screen that makes the hybrid site role honest. Do not "simplify" it
// down to the effective role: a listing that cannot tell a live directory membership
// apart from a stale local grant is the thing that turns the second into a backdoor.
func (a *API) handleListSiteAdmins(w http.ResponseWriter, r *http.Request) error {
	ctx := r.Context()

	rows, err := a.store.ListSiteAdmins(ctx)
	if err != nil {
		return fmt.Errorf("list site admins: %w", err)
	}

	out := make([]SiteAdmin, 0, len(rows))

	for _, row := range rows {
		out = append(out, newSiteAdmin(row))
	}

	writeJSON(w, http.StatusOK, list(out))

	return nil
}

// handlePutSiteAdmin grants another user a LOCAL site-admin role. Site admin only.
//
// # Why the flag is checked here and the route is still registered
//
// --allow-local-site-admins=false closes this path for everyone, site admins
// included. Unlike dev-login -- whose route is not registered at all when it is off,
// because a 403 there would tell an unauthenticated scanner which flag to hunt for --
// this endpoint already sits behind site admin. There is nobody to hide it from who
// could not otherwise see it, and a site admin who tries needs to be told WHY it was
// refused rather than being handed a 404 that reads as a bug.
//
// Note it does not gate the CLI break-glass, and must not: a deployment with the flag
// off and no site admin would otherwise have no way to appoint its first one.
func (a *API) handlePutSiteAdmin(w http.ResponseWriter, r *http.Request) error {
	ctx := r.Context()

	p, ok := principalFrom(ctx)
	if !ok {
		return errUnauthorized("authentication required")
	}

	if !a.allowLocalSiteAdmins {
		return errForbidden("local site-admin grants are disabled on this installation " +
			"(--allow-local-site-admins=false). Site administrators are derived from OIDC " +
			"group claims: add the user to a group listed in site_admin_groups.")
	}

	user, err := a.resolveUser(ctx, r.PathValue("user"))
	if err != nil {
		return err
	}

	// granted_by is the CALLER, and the guard has already established that they are a
	// site admin AND not an API key. The column is nullable only so the CLI break-glass
	// -- which has no session -- can leave it empty.
	granted, err := a.store.GrantSiteAdminLocal(ctx, repository.GrantSiteAdminLocalParams{
		ID:        user.ID,
		GrantedBy: p.UserID(),
	})
	if err != nil {
		return fmt.Errorf("grant local site admin: %w", err)
	}

	// A site-admin grant is the loudest thing that happens in this installation. Log
	// it at INFO with both parties named, so it lands in the aggregator whether or not
	// anyone ever opens the listing.
	a.log.InfoContext(ctx, "granted a local site-admin role",
		slog.String("user", user.Email),
		slog.String("granted_by", p.Email()),
	)

	writeJSON(w, http.StatusOK, newSiteAdminFromUser(granted, p.Email()))

	return nil
}

// handleDeleteSiteAdmin clears a user's LOCAL site-admin grant. Site admin only.
//
// It is deliberately NOT gated on --allow-local-site-admins. Turning that flag off is
// exactly the moment an operator needs to clean up the local grants that predate it,
// and a revocation path that the lockdown switch disables is a lockdown switch that
// entrenches what it was meant to remove.
//
// The three outcomes, which are NOT interchangeable:
//
//  1. Local grant only. The grant is cleared and the user is no longer a site admin.
//
//  2. Local grant AND an OIDC claim. The local half is cleared and THE USER IS STILL
//     A SITE ADMIN, by group claim, with every privilege in the installation. 200,
//     still_a_site_admin = TRUE, and the body names the group holding it up. An
//     operator who reads a bare 204 as "demoted" is wrong, and a bare 204 is what
//     would have told them so.
//
//  3. No local grant. There is nothing here to remove. A claim-derived site admin is
//     a 409 -- removing them means removing them from the group in the IdP -- and
//     someone who is not a site admin at all is a 404.
func (a *API) handleDeleteSiteAdmin(w http.ResponseWriter, r *http.Request) error {
	ctx := r.Context()

	user, err := a.resolveUser(ctx, r.PathValue("user"))
	if err != nil {
		return err
	}

	if !user.SiteRoleLocal.Valid {
		if user.SiteRoleOidc.Valid {
			return errConflict(CodeClaimDerived, "this site-admin role is derived from OIDC group "+
				"claims"+siteClaimSource(user)+", not from a grant made here, so it cannot be removed "+
				"here. Remove the user from the group in the identity provider, or from "+
				"site_admin_groups, and the role disappears at their next login.")
		}

		return errNotFound("that user holds no local site-admin grant")
	}

	revoked, err := a.store.RevokeSiteAdminLocal(ctx, user.ID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// A concurrent revocation cleared the grant between the read above and this
			// write. The guard in the SQL held; nothing is wrong except that there was
			// nothing left to do.
			return errConflict(CodeConflict,
				"the site-admin grant changed while it was being removed; retry")
		}

		return fmt.Errorf("revoke local site admin: %w", err)
	}

	stillAdmin := revoked.SiteRole == auth.SiteRoleAdmin

	a.log.InfoContext(ctx, "revoked a local site-admin role",
		slog.String("user", user.Email),
		slog.Bool("still_a_site_admin", stillAdmin),
	)

	if !stillAdmin {
		writeJSON(w, http.StatusOK, SiteAdminRemoval{
			UserID: uuidString(user.ID), LocalRoleRevoked: true, StillASiteAdmin: false,
			Admin:   nil,
			Message: "The local site-admin grant was removed. This user is no longer a site administrator.",
		})

		return nil
	}

	admin := newSiteAdminFromUser(revoked, "")

	writeJSON(w, http.StatusOK, SiteAdminRemoval{
		UserID: uuidString(user.ID), LocalRoleRevoked: true, StillASiteAdmin: true,
		Admin: &admin,
		Message: "The local grant was removed, but this user IS STILL A SITE ADMINISTRATOR: " +
			"their OIDC group claims" + siteClaimSource(revoked) + " make them one on their own. " +
			"To remove the role entirely, remove them from the group in the identity provider.",
	})

	return nil
}

// siteClaimSource names the group behind a claim-derived site role, for the prose in
// the two responses above. An operator's next question is always "held up by WHAT?".
func siteClaimSource(u repository.User) string {
	if !u.SiteOidcGroup.Valid || u.SiteOidcGroup.String == "" {
		return ""
	}

	return " (" + u.SiteOidcGroup.String + ")"
}
